[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "freddy_2_docs"
authors = [{name = "KishanSawant", email = "kishansawant96@gmail.com"}]
dynamic = ["version", "description"]